parameters:
            database_driver: pdo_mysql
            database_host: 127.0.0.1
            database_port: null
            database_name: siteaionrising
            database_user: root
            database_password: null 
            database_driver2: pdo_mysql
            database_host2: 127.0.0.1
            database_port2: null
            database_name2: gameserver
            database_user2: root
            database_password2: null
            mailer_transport: smtp
            mailer_host: 127.0.0.1
            mailer_user: null
            mailer_password: null
            locale: en
            secret: ThisTokenIsNotSoSecretChangeIt
            debug_toolbar: true
            debug_redirects: false
            use_assetic_controller: true 
           