site_rising_accueil:
    path:   /
    defaults: {_controller: SiteRisingAionBundle:Index:index }
    
site_rising_joinUs:
    path: /joinUs
    defaults: {_controller: SiteRisingAionBundle:Index:joinUs }
    
site_rising_userProfile:
    path: /profile
    defaults: {_controller: SiteRisingAionBundle:Index:userProfile }

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    