parameters:
#    site_rising_aion.example.class: SiteRising\AionBundle\Example

services:
#    site_rising_aion.example:
#        class: %site_rising_aion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
