<?php

namespace SiteRising\AionShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmplacementAutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementAutreRepository extends EntityRepository
{
    
}
